/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AnimalTest {
@Test
public void instantiatesWell(){
  Animal myAnimal=new Animal("lion","collins","endangered");
  assertTrue(myAnimal instanceof Animal);
}
}
